# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-16 19:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_u1', models.BooleanField(default=False)),
                ('res_u2', models.BooleanField(default=False)),
                ('user_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GameUser1', to=settings.AUTH_USER_MODEL)),
                ('user_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GameUser2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Game', to='game.GameDetail')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(default='Media/index.png', upload_to=game.models.upload_profile_pic_path)),
                ('is_primary', models.BooleanField(default=False)),
                ('consensus', models.BooleanField(default=False)),
                ('prim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SecondaryRelation', to='game.Image')),
            ],
        ),
        migrations.CreateModel(
            name='QuesResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GameRes', to='game.GameQuestions')),
                ('res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Response', to='game.Image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserRes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gamequestions',
            name='ques',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GameQuestions', to='game.Image'),
        ),
    ]
