# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-16 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='prim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SecondaryRelation', to='game.Image'),
        ),
    ]
